### ISSUE TITLE
Updated schematic JSON...

### ISSUE THREAD

**Issue by ApplicationNinja** [DanielLCopeland/ESP-R8-POE-3C#1]
Is there a schematic .json file, as there was one with the 3B version?

Thank you...

**Comment by nixietheskwerl** [comment]
The repository has been updated, and the EasyEDA schematic file can now be found in the "design_files" folder in the repository.  Sorry for taking so long to get back to you.

https://github.com/DanielLCopeland/ESP-R8-POE-3C/tree/main/design_files

**Comment by ApplicationNinja** [comment]
Great, thank you!

**Comment by ApplicationNinja** [comment]
Great, thank you!
